spring:
  docker:
    compose:
      enabled: false
  application:
    name: FashionShop
  datasource:
    url: "jdbc:mysql://localhost:3306/fashion_shop"
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 5MB
      max-file-size: 5MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs