spring:
  data:
    redis:
      host: redis-18620.c1.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 18620
      username: default
      password: iJA8gzweshOAnISRVc4GmX5CoXClxoRZ
      ssl:
        enabled: true
  cache:
    type: redis

  docker:
    compose:
      enabled: false
  application:
    name: fashionShop-service
  datasource:
    url: "jdbc:mysql://localhost:3306/fashion_shop"
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-request-size: 5MB
      max-file-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: huydlx@gmail.com
    password: wero islt wcbc ykvf
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations: D:\\Java\\FashionShop\\images
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true
#  api-docs:
#    path: /v3/api-docs

jwt:
  signerKey: "Nl0EwgZ2zY7r2lfXYJOUguERWZkvn3KDPu6pK+9EWFMsqCfywwzmhViCGawL2qQN"

storage:
  location: D:\\Java\\FashionShop\\images

VNPay:
  vnp_PayUrl: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  vnp_ReturnUrl: "http://localhost:8080/api/payments/returnStatus"
  vnp_TmnCode: "5WBEBV7X"
  vnp_HashSecret: "RQTDJY26UYM1G5AFFRT9WH9WSKB1W1FL"




