spring:
  docker:
    compose:
      enabled: false
  application:
    name: fashionShop-service
  datasource:
    url: "jdbc:mysql://localhost:3306/fashion_shop"
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-request-size: 5MB
      max-file-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: huydlx@gmail.com
    password: wero islt wcbc ykvf
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

jwt:
  signerKey: "Nl0EwgZ2zY7r2lfXYJOUguERWZkvn3KDPu6pK+9EWFMsqCfywwzmhViCGawL2qQN"



